### ISSUE TITLE
[BUG]: `v0.8.13` breaks because of a circular import

### ISSUE THREAD

**Issue by daavoo** [ComposioHQ/composio#1946]
This bug was introduced in https://github.com/ComposioHQ/composio/pull/1937

- Reproduce

Running:

``` 
uv run --no-project --with composio python -c "import composio"
```

Fails with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import composio
  File "/tmp/.tmpti3vB2/archive-v0/-O3nrC1cKZDrEDl-yANvI/lib/python3.13/site-packages/composio/__init__.py", line 2, in <module>
    from .core.models.tools import (
    ...<3 lines>...
    )
  File "/tmp/.tmpti3vB2/archive-v0/-O3nrC1cKZDrEDl-yANvI/lib/python3.13/site-packages/composio/core/models/__init__.py", line 4, in <module>
    from .tools import Tools
  File "/tmp/.tmpti3vB2/archive-v0/-O3nrC1cKZDrEDl-yANvI/lib/python3.13/site-packages/composio/core/models/tools.py", line 27, in <module>
    from composio.types import ToolkitVersionParam
  File "/tmp/.tmpti3vB2/archive-v0/-O3nrC1cKZDrEDl-yANvI/lib/python3.13/site-packages/composio/types.py", line 8, in <module>
    from composio.core.models.tools import (
    ...<3 lines>...
    )
ImportError: cannot import name 'Modifiers' from partially initialized module 'composio.core.models.tools' (most likely due to a circular import) (/tmp/.tmpti3vB2/archive-v0/-O3nrC1cKZDrEDl-yANvI/lib/python3.13/site-packages/composio/core/models/tools.py)
```
